### ISSUE TITLE
Problem with building a network in ScienceScape

### ISSUE THREAD

**Issue by EmanuelBonn** [medialab/sciencescape#2]
I have exported a CSV file from Scopus and when I uploaded it in ScienceScape in "Get Network", it sucks every time while building a network. The other visualisations does not work either. It says "extraction failed". 
Maybe I should have fix something in CSV file? 
Here is my file: 

https://www.dropbox.com/s/ce88d9hg814o6wb/Scopus-1613-Analyze-Year-2.csv?dl=0

Stefan

**Comment by boogheta** [comment]
Hi,

It looks like the format of your file is not what ScienceScape takes as inputs from Scopus.

Here's the link to a video tutorial explaning how to download Scopus data with the right format.

**Comment by EmanuelBonn** [comment]
Thanks it helped :+1:
